disabled_rules:
- identifier_name
- trailing_whitespace
- type_name
- syntactic_sugar
- todo

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

function_body_length:
- 69 # warning
- 70 # error

file_length:
- 1499  # warning
- 1500 # error

type_body_length:
- 300 # warning
- 400 # error

line_length:
- 270 # warning
- 300 # error

cyclomatic_complexity:
- 10  # warning
- 11 # error

excluded:
- Carthage
