disabled_rules:
- identifier_name
- trailing_whitespace
- type_name
- syntactic_sugar

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

function_body_length:
- 55 # warning
- 60 #error

file_length:
- 930 # warning
- 1000 # error

type_body_length:
- 300 # warning
- 400 # error

line_length:
- 230 # warning
- 250 # error

cyclomatic_complexity:
- 9 # warning
- 12 # error

excluded:
- Carthage
