disabled_rules:
- identifier_name
- trailing_whitespace
- type_name
- syntactic_sugar
- todo
- implicit_getter

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

function_body_length:
- 79 # warning
- 80 # error

file_length:
- 1499  # warning
- 1500 # error

type_body_length:
- 300 # warning
- 400 # error

line_length:
- 270 # warning
- 300 # error

cyclomatic_complexity:
- 11  # warning
- 12 # error

excluded:
- Carthage
- Package.swift
- Tests/RVS_BlueThoth_Test_Harness_WatchOS/RVS_BlueThoth_Test_Harness_WatchOS_Extension
- Tests/RVS_BlueThoth_Test_Harness_tvOS
