disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- type_name
- function_body_length
- weak_delegate
- large_tuple
- todo
- inert_defer
- reduce_boolean
- syntactic_sugar

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

file_length:
- 3000 # warning
- 3001 # error

type_body_length:
- 1000 # warning
- 1001 # error

line_length:
- 400 # warning
- 401 # error

cyclomatic_complexity:
- 23 # warning
- 24 # error

excluded:
- test
- docs
